#
# EcoSkills
# by Auxilor
#

mysql:
  enabled: false # Set to false, data.yml will be used instead.
  host: localhost
  port: 3306
  database: database
  user: username
  password: passy

gui:
  rows: 6

  line-wrap: 40

  mask:
    # The way the mask works is by having a list of materials
    # And then a pattern to use those materials.

    # The pattern is the rows in the GUI
    # Each line must be 9 long, and the amount of rows should be the amount of rows in the GUI
    # A zero represents nothing
    # A 1 represents the first material
    # A 2 represents the second material
    # And so on, you can add up to 9.

    materials:
      - black_stained_glass_pane
    pattern:
      - "111101111"
      - "111111111"
      - "110000011"
      - "110010011"
      - "111111111"
      - "111101111"

  player-info:
    row: 1
    column: 5

    name: "&f%player%&f's &fStats:"
    lore:
      - "&f"
      - " %ecoskills_defense_name%&f %ecoskills_defense_base% &e%ecoskills_defense_bonus%"
      - " %ecoskills_strength_name%&f %ecoskills_strength_base% &e%ecoskills_strength_bonus%"
      - " %ecoskills_crit_chance_name%&f %ecoskills_crit_chance_base%% &e%ecoskills_crit_chance_bonus%"
      - " %ecoskills_crit_damage_name%&f %ecoskills_crit_damage_base% &e%ecoskills_crit_damage_bonus%"
      - " %ecoskills_speed_name%&f %ecoskills_speed_base% &e%ecoskills_speed_bonus%"
      - " %ecoskills_wisdom_name%&f %ecoskills_wisdom_base% &e%ecoskills_wisdom_bonus%"
      - " %ecoskills_ferocity_name%&f %ecoskills_ferocity_base% &e%ecoskills_ferocity_bonus%"
      - "&f"
      - "&7Total Skill Level: &f%ecoskills_total_skill_level%"
      - "&7Average Skill Level: &f%ecoskills_average_skill_level%"

  close:
    material: barrier
    name: "&cClose"
    location:
      row: 6
      column: 5

  skill-icon:
    name: "&#ff00ae%skill% &d%level_numeral%"
    lore:
      - "&8&o%description%"
      - "&f"
      - "%skill_specific%"
      - "&f"
      - "&fProgress to next level:"
      - "&8Â» &e%percentage_progress%"
      - "&8Â» &e%current_xp%&8/&7%required_xp% &fXP"
      - "&f"
      - "&eClick to view Level Progression!"

level-gui:
  rows: 6

  mask:
    # The way the mask works is by having a list of materials
    # And then a pattern to use those materials.

    # The pattern is the rows in the GUI
    # Each line must be 9 long, and the amount of rows should be the amount of rows in the GUI
    # A zero represents nothing
    # A 1 represents the first material
    # A 2 represents the second material
    # And so on, you can add up to 9.

    materials:
      - black_stained_glass_pane
    pattern:
      - "111111111"
      - "111111111"
      - "111111111"
      - "111111111"
      - "111111111"
      - "111111111"

  progression-slots:
    # To set the order of the pattern,
    # Use 1-9 and then a-z: a goes after 9.
    pattern:
      - "109ab0jkl"
      - "2080c0i0m"
      - "3070d0h0n"
      - "4560efg0o"
      - "00000000p"
      - "00000000q"

    # If the amount of the item should be the level
    level-as-amount: true

    prev-page:
      material: arrow
      name: "&fPrevious Page"
      location:
        row: 6
        column: 4

    next-page:
      material: arrow
      name: "&fNext Page"
      location:
        row: 6
        column: 6

    close:
      material: barrier
      name: "&cClose"
      location:
        row: 6
        column: 5

    unlocked:
      material: lime_stained_glass_pane
      name: "&a%skill% Level %level_numeral%"
      lore:
        - "&f"
        - "&fRewards:"
        - "%rewards%"
        - "&f"
        - "&aUNLOCKED"
    in-progress:
      material: yellow_stained_glass_pane
      name: "&e%skill% Level %level_numeral%"
      lore:
        - "&f"
        - "&fRewards:"
        - "%rewards%"
        - "&f"
        - "&fProgress:"
        - "&8Â» &e%percentage_progress%"
        - "&8Â» &e%current_xp%&8/&7%required_xp% &fXP"
    locked:
      material: red_stained_glass_pane
      name: "&c%skill% Level %level_numeral%"
      lore:
        - "&f"
        - "&fRewards:"
        - "%rewards%"

  close:
    material: barrier
    name: "&cClose"
    location:
      row: 6
      column: 5

  skill-icon:
    name: "&#ff00ae%skill% &d%level_numeral%"
    lore:
      - "&8&o%description%"
      - "&f"
      - "%skill_specific%"
      - "&f"
      - "&fProgress to next level:"
      - "&8Â» &e%percentage_progress%"
      - "&8Â» &e%current_xp%&8/&7%required_xp% &fXP"
      - "&f"
      - "&eClick to view Level Progression!"

skills:
  # Add more levels depending on the highest max level for all skills
  level-xp-requirements:
    - 50
    - 125
    - 200
    - 300
    - 500
    - 750
    - 1000
    - 1500
    - 2000
    - 3500
    - 5000
    - 7500
    - 10000
    - 15000
    - 20000
    - 30000
    - 50000
    - 75000
    - 100000
    - 200000
    - 300000
    - 400000
    - 500000
    - 600000
    - 700000
    - 800000
    - 900000
    - 1000000
    - 1100000
    - 1200000
    - 1300000
    - 1400000
    - 1500000
    - 1600000
    - 1700000
    - 1800000
    - 1900000
    - 2000000
    - 2100000
    - 2200000
    - 2300000
    - 2400000
    - 2500000
    - 2600000
    - 2750000
    - 2900000
    - 3100000
    - 3400000
    - 3700000
    - 4000000

  prevent-levelling-while-afk: true # If the player is afk (Essentials) then don't give xp

  # Ways to tell the player about skill progress
  progress:
    action-bar:
      # If the action bar should be used
      enabled: true
      # The actionbar message that should be sent
      format: "&f%skill% &8| &9(%current_xp%/%required_xp%) &e+%gained_xp%"
    sound:
      # If a sound should be played
      enabled: true
      # The sound that should be played
      id: entity_experience_orb_pickup
      # Pitch between 0.5 and 2
      pitch: 2
      # The volume
      volume: 0.1

  # Ways to tell the player about levelling up
  level-up:
    message:
      level-as-numeral: true
      enabled: true
      message:
        - "&f"
        - " &#ff00aeYou levelled up &d%skill%&#ff00ae to &eLevel %level%&#ff00ae!"
        - "&f"
        - " &#ff00ae&lREWARDS:"
        - "%rewards%"
        - "&f"
    sound:
      # If a sound should be played
      enabled: true
      # The sound that should be played
      id: entity_player_levelup
      # Pitch between 0.5 and 2
      pitch: 0.8

stats:
  defense:
    name: "&#e884b0ðŸ›¡ Defense"
    # 100% halves the incoming damage
    percent-less-damage-per-level: 1
  strength:
    name: "&#db0000ðŸ—¡ Strength"
    # 100% is double damage
    percent-more-damage-per-level: 1
  crit_chance:
    name: "&#f7ff85â˜£ Crit Chance"
    # Nothing happens above 100%, 200% is the same as it.
    chance-per-level: 1
  crit_damage:
    name: "&9â˜  Crit Damage"
    # The percent more damage to deal on crits for each level.
    percent-more-damage-per-level: 2
    # The amount more damage to deal on crits by default.
    base-percent-more: 50
  speed:
    name: "&#40ffe6âœ¦ Speed"
    # The percent more speed to give for the speed attribute (internal in the game)
    # for each level
    percent-faster-per-level: 1
  wisdom:
    name: "&#42f566âœŽ Wisdom"
    # The percent more xp to gain from orbs for each level of the stat.
    percent-more-xp-gain: 1
  ferocity:
    name: "&#6b0000â«½ Ferocity"
    # The percent chance to deal damage twice
    chance-per-level: 0.5

damage-indicators:
  # Requires HolographicDisplays/GHolo to be installed
  enabled: true
  format:
    normal: "&7%damage%"
    crit: "&fâœ§ <gradient:#f953c6>%damage%</gradient:#b91d73> &fâœ§"
  max-x-offset: 0.6
  max-y-offset: 0.6
  max-z-offset: 0.6

commands:
  top:
    # If displayname (including rank) should be used
    use-display-name: true

autosave:
  log: true # If auto-save messages should be sent to console
  async: false # If saves should be performed asynchronously. May cause bugs without MySQL