#
# EcoSkills
# by Auxilor
#

# Go to /plugins/eco/config.yml to change MySQL settings

gui:
  rows: 6

  line-wrap: 40

  mask:
    # The way the mask works is by having a list of materials
    # And then a pattern to use those materials.

    # The pattern is the rows in the GUI
    # Each line must be 9 long, and the amount of rows should be the amount of rows in the GUI
    # A zero represents nothing
    # A 1 represents the first material
    # A 2 represents the second material
    # And so on, you can add up to 9.

    materials:
      - black_stained_glass_pane
    pattern:
      - "111101111"
      - "111111111"
      - "110000011"
      - "110010011"
      - "111111111"
      - "111101111"

  player-info:
    row: 1
    column: 5

    click-to-open-stats: true

    name: "&f%player%&f's &fStats:"
    lore:
      - "&f"
      - " %ecoskills_defense_name%&f %ecoskills_defense_base% &e%ecoskills_defense_bonus%"
      - " %ecoskills_strength_name%&f %ecoskills_strength_base% &e%ecoskills_strength_bonus%"
      - " %ecoskills_crit_chance_name%&f %ecoskills_crit_chance_base%% &e%ecoskills_crit_chance_bonus%"
      - " %ecoskills_crit_damage_name%&f %ecoskills_crit_damage_base% &e%ecoskills_crit_damage_bonus%"
      - " %ecoskills_speed_name%&f %ecoskills_speed_base% &e%ecoskills_speed_bonus%"
      - " %ecoskills_wisdom_name%&f %ecoskills_wisdom_base% &e%ecoskills_wisdom_bonus%"
      - " %ecoskills_ferocity_name%&f %ecoskills_ferocity_base% &e%ecoskills_ferocity_bonus%"
      - "&f"
      - "&7Total Skill Level: &f%ecoskills_total_skill_level%"
      - "&7Average Skill Level: &f%ecoskills_average_skill_level%"
      - ""
      - "&eClick to view more!"

  close:
    material: barrier
    name: "&cClose"
    location:
      row: 6
      column: 5

  skill-icon:
    name: "&#ff00ae%skill% &d%level_numeral%"
    lore:
      - "&8&o%description%"
      - "&f"
      - "%skill_specific%"
      - "&f"
      - "&fProgress to next level:"
      - "&8¬ª &e%percentage_progress%"
      - "&8¬ª &e%current_xp%&8/&7%required_xp% &fXP"
      - "&f"
      - "&eClick to view Level Progression!"

stats-gui:
  rows: 6

  mask:
    # The way the mask works is by having a list of materials
    # And then a pattern to use those materials.

    # The pattern is the rows in the GUI
    # Each line must be 9 long, and the amount of rows should be the amount of rows in the GUI
    # A zero represents nothing
    # A 1 represents the first material
    # A 2 represents the second material
    # And so on, you can add up to 9.

    materials:
      - black_stained_glass_pane
    pattern:
      - "111101111"
      - "111111111"
      - "101010101"
      - "110101011"
      - "111111111"
      - "011111111"

  player-info:
    row: 1
    column: 5

    name: "&f%player%&f's &fStats:"
    lore:
      - "&f"
      - " %ecoskills_defense_name%&f %ecoskills_defense_base% &e%ecoskills_defense_bonus%"
      - " %ecoskills_strength_name%&f %ecoskills_strength_base% &e%ecoskills_strength_bonus%"
      - " %ecoskills_crit_chance_name%&f %ecoskills_crit_chance_base%% &e%ecoskills_crit_chance_bonus%"
      - " %ecoskills_crit_damage_name%&f %ecoskills_crit_damage_base% &e%ecoskills_crit_damage_bonus%"
      - " %ecoskills_speed_name%&f %ecoskills_speed_base% &e%ecoskills_speed_bonus%"
      - " %ecoskills_wisdom_name%&f %ecoskills_wisdom_base% &e%ecoskills_wisdom_bonus%"
      - " %ecoskills_ferocity_name%&f %ecoskills_ferocity_base% &e%ecoskills_ferocity_bonus%"
      - "&f"
      - "&7Total Skill Level: &f%ecoskills_total_skill_level%"
      - "&7Average Skill Level: &f%ecoskills_average_skill_level%"

  back:
    material: arrow
    name: "&fBack"
    location:
      row: 6
      column: 1

level-gui:
  rows: 6

  mask:
    # The way the mask works is by having a list of materials
    # And then a pattern to use those materials.

    # The pattern is the rows in the GUI
    # Each line must be 9 long, and the amount of rows should be the amount of rows in the GUI
    # A zero represents nothing
    # A 1 represents the first material
    # A 2 represents the second material
    # And so on, you can add up to 9.

    materials:
      - black_stained_glass_pane
    pattern:
      - "111111111"
      - "111111111"
      - "111111111"
      - "111111111"
      - "111111111"
      - "111111111"

  progression-slots:
    # To set the order of the pattern,
    # Use 1-9 and then a-z: a goes after 9.
    pattern:
      - "109ab0jkl"
      - "2080c0i0m"
      - "3070d0h0n"
      - "4560efg0o"
      - "00000000p"
      - "00000000q"

    # If the amount of the item should be the level
    level-as-amount: true

    prev-page:
      material: arrow
      name: "&fPrevious Page"
      location:
        row: 6
        column: 4

    next-page:
      material: arrow
      name: "&fNext Page"
      location:
        row: 6
        column: 6

    close:
      material: barrier
      name: "&cClose"
      location:
        row: 6
        column: 5

    unlocked:
      material: lime_stained_glass_pane
      name: "&a%skill% Level %level_numeral%"
      lore:
        - "&f"
        - "&fRewards:"
        - "%rewards%"
        - "&f"
        - "&aUNLOCKED"
    in-progress:
      material: yellow_stained_glass_pane
      name: "&e%skill% Level %level_numeral%"
      lore:
        - "&f"
        - "&fRewards:"
        - "%rewards%"
        - "&f"
        - "&fProgress:"
        - "&8¬ª &e%percentage_progress%"
        - "&8¬ª &e%current_xp%&8/&7%required_xp% &fXP"
    locked:
      material: red_stained_glass_pane
      name: "&c%skill% Level %level_numeral%"
      lore:
        - "&f"
        - "&fRewards:"
        - "%rewards%"

  close:
    material: barrier
    name: "&cClose"
    location:
      row: 6
      column: 5

  skill-icon:
    name: "&#ff00ae%skill% &d%level_numeral%"
    lore:
      - "&8&o%description%"
      - "&f"
      - "%skill_specific%"
      - "&f"
      - "&fProgress to next level:"
      - "&8¬ª &e%percentage_progress%"
      - "&8¬ª &e%current_xp%&8/&7%required_xp% &fXP"
      - "&f"
      - "&eClick to view Level Progression!"

skills:
  prevent-levelling-while-afk: true # If the player is afk (Essentials) then don't give xp

  # Ways to tell the player about skill progress
  progress:
    action-bar:
      # If the action bar should be used
      enabled: true
      # The actionbar message that should be sent
      format: "&f%skill% &8| &9(%current_xp%/%required_xp%) &e+%gained_xp%"
    boss-bar:
      # If the boss bar should be used
      enabled: false
      # The boss bar message that should be sent
      format: "&f%skill% &8| &9(%current_xp%/%required_xp%)"
      # The color of the boss bar (from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html)
      color: blue
      # The style of the boss bar (from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html)
      style: solid
      # How long the boss bar should last (in milliseconds)
      duration: 2500
    sound:
      # If a sound should be played
      enabled: true
      # The sound that should be played
      id: entity_experience_orb_pickup
      # Pitch between 0.5 and 2
      pitch: 2
      # The volume
      volume: 0.1

  # Ways to tell the player about levelling up
  level-up:
    message:
      level-as-numeral: true
      enabled: true
      message:
        - "&f"
        - " &#ff00aeYou levelled up &d%skill%&#ff00ae to &eLevel %level%&#ff00ae!"
        - "&f"
        - " &#ff00ae&lREWARDS:"
        - "%rewards%"
        - "&f"
    sound:
      # If a sound should be played
      enabled: true
      # The sound that should be played
      id: entity_player_levelup
      # Pitch between 0.5 and 2
      pitch: 0.8

stats:
  defense:
    name: "&#e884b0üõ° Defense"

    description: "&8Take &a%percent_less_damage%%&8 less damage" # The description to be shown in lore and messages

    stats-gui:
      enabled: true
      position:
        row: 3
        column: 2
      item:
        item: player_head texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjlhODczZjI0OGMzOTExMjIxODg3OWNjOWMwMzM0N2VkMTZlN2Y2MDIzOTBhYzdhNjgwNmY4ZTg0OTI3OTRkNSJ9fX0=
        name: "%stat%"
        lore:
          - "&fLevel: &a%level%"
          - "&8&o%description%"

    # Disabled worlds
    disabled-in-worlds: [ ]
    # 100% halves the incoming damage
    percent-less-damage-per-level: 0.25
  strength:
    name: "&#db0000üó° Strength"

    description: "&8Deal &a%percent_more_damage%%&8 more damage" # The description to be shown in lore and messages

    stats-gui:
      enabled: true
      position:
        row: 3
        column: 4
      item:
        item: player_head texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWRmOTZjY2Q5Mjk5MGRkOGI4NTUzZDJjY2VhYjRjMmM5YjIwOGFhMjI1ZGIxNTc1ODJmY2Q1NjY5MTVkNGJjZiJ9fX0=
        name: "%stat%"
        lore:
          - "&fLevel: &a%level%"
          - "&8&o%description%"

    # Disabled worlds
    disabled-in-worlds: [ ]
    # 100% is double damage
    percent-more-damage-per-level: 0.25
  crit_chance:
    name: "&#f7ff85‚ò£ Crit Chance"

    description: "&8Gives you a &a%chance%%&8 chance to deal crits" # The description to be shown in lore and messages

    stats-gui:
      enabled: true
      position:
        row: 3
        column: 6
      item:
        item: player_head texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmFiMTgwZTgyMGY3MTYyOWYwMWYyNWI2MmJkZWI5YzMyNGQ1MGEzOGFmNzRlNmE5MzIxNDM5NDcxMDQ2ZGM0MSJ9fX0=
        name: "%stat%"
        lore:
          - "&fLevel: &a%level%"
          - "&8&o%description%"

    # Nothing happens above 100%, 200% is the same as it.
    chance-per-level: 1
  crit_damage:
    name: "&9‚ò† Crit Damage"

    description: "&8Crits deal &a%percent_more_damage%%&8 more damage" # The description to be shown in lore and messages

    stats-gui:
      enabled: true
      position:
        row: 3
        column: 8
      item:
        item: player_head texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2UzN2RmMjdkMWU5MjVkMmY3OGRlNjkzNDEzYWRhYjc1ZDc5MTg4NDViYWM4ZjYxNzRmZGIyMmVjNTc3NjExZCJ9fX0=
        name: "%stat%"
        lore:
          - "&fLevel: &a%level%"
          - "&8&o%description%"

    # Disabled worlds
    disabled-in-worlds: [ ]
    # The percent more damage to deal on crits for each level.
    percent-more-damage-per-level: 0.5
    # The amount more damage to deal on crits by default.
    base-percent-more: 50
  speed:
    name: "&#40ffe6‚ú¶ Speed"

    description: "&8Makes you move &a%percent_faster%%&8 faster" # The description to be shown in lore and messages

    stats-gui:
      enabled: true
      position:
        row: 4
        column: 3
      item:
        item: player_head texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODYyNGJhY2I1ZjE5ODZlNjQ3N2FiY2U0YWU3ZGNhMTgyMGE1MjYwYjYyMzNiNTViYTFkOWJhOTM2Yzg0YiJ9fX0=
        name: "%stat%"
        lore:
          - "&fLevel: &a%level%"
          - "&8&o%description%"

    # Disabled worlds
    disabled-in-worlds: [ ]
    # The percent more speed to give for the speed attribute (internal in the game)
    # for each level
    percent-faster-per-level: 1
  wisdom:
    name: "&#42f566‚úé Wisdom"

    description: "&8Increases xp gain by &a%percent_more_xp%%" # The description to be shown in lore and messages

    stats-gui:
      enabled: true
      position:
        row: 4
        column: 5
      item:
        item: player_head texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzA1NGMyOWM3ODA5MDQ3MWMxZWEwNThiZDY0MTg5NzM5MWM5ZTQ2OTRhYTlkMTQwYWZiYmE4ZDBjYzQzNjM3In19fQ==
        name: "%stat%"
        lore:
          - "&fLevel: &a%level%"
          - "&8&o%description%"

    # Disabled worlds
    disabled-in-worlds: [ ]
    # The percent more xp to gain from orbs for each level of the stat.
    percent-more-xp-gain: 1
  ferocity:
    name: "&#6b0000‚´Ω Ferocity"

    description: "&8Gives a &a%chance%%&8 chance to deal damage twice" # The description to be shown in lore and messages

    stats-gui:
      enabled: true
      position:
        row: 4
        column: 7
      item:
        item: player_head texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjk2YTYzNTMwZjhmNGVkMzBhMWQzNjg2ZTk4OGY2NzYzMDBlNGYxODE0MDllMDc4YWUzMGY5ZTA2NDZmYjI3ZCJ9fX0=
        name: "%stat%"
        lore:
          - "&fLevel: &a%level%"
          - "&8&o%description%"

    # Disabled worlds
    disabled-in-worlds: [ ]
    # The percent chance to deal damage twice
    chance-per-level: 0.5
  health:
    name: "&c‚ù§ Health"

    description: "&8Gives &a+%health%&8 health" # The description to be shown in lore and messages

    stats-gui:
      enabled: false
      position:
        row: 5
        column: 4
      item:
        item: player_head texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWNhYTc0NDZiZTg3NGJmMWExNGVkMWZjZWZjYzBhMDkyMzM2YzFiZjViZjQ2NWU5ZDI1NGRlZTM0YWZlYTc5In19fQ==
        name: "%stat%"
        lore:
          - "&fLevel: &a%level%"
          - "&8&o%description%"

    # Disabled worlds
    disabled-in-worlds: [ ]
    # The extra hp per level
    health-per-level: 1
  attack_speed:
    name: "&#fcba03‚öî Attack Speed"

    description: "&8Increases your attack speed by &a%percent_faster%%" # The description to be shown in lore and messages

    stats-gui:
      enabled: false
      position:
        row: 5
        column: 6
      item:
        item: player_head texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmJiOGQ3MjU5YzhlNzI1ZTdjZjc1ODFjNzY5YWRkNDIyMmU3NjY3NWZlOTZlZDAxYWQ3YjRkYjdkNTU0ZjRhMyJ9fX0=
        name: "%stat%"
        lore:
          - "&fLevel: &a%level%"
          - "&8&o%description%"

    # Disabled worlds
    disabled-in-worlds: [ ]
    # The percent more speed to give for the speed attribute (internal in the game)
    # for each level
    percent-faster-per-level: 1

damage-indicators:
  # Requires HolographicDisplays/GHolo/CMI to be installed
  enabled: true
  final-damage: false # If final damage (with reductions applied) should be used.
  format:
    normal: "&7%damage%"
    crit: "&f‚úß <gradient:#f953c6>%damage%</gradient:#b91d73> &f‚úß"
  healing:
    enabled: true
    format: "&a+%damage%"
  max-x-offset: 0.6
  max-y-offset: 0.6
  max-z-offset: 0.6

# A constant action bar showing health and any other information to all players online
persistent-action-bar:
  # If the persistent action bar should be enabled
  enabled: true
  # If a player's health should be scaled to always display as 10 hearts.
  scale-health: true
  # The format
  format: "&c‚ù§ &f%player_health_rounded%&8/&f%player_max_health_rounded%                 &#e884b0üõ° &f%ecoskills_defense% &8| &#db0000üó° &f%ecoskills_strength% &8| &#40ffe6‚ú¶ &f%ecoskills_speed%"
  # Time from blacklist -> unblacklist (in milliseconds). Action bar messages are 2000 + 1000 fade,
  # you can set it to a lower value to last for less of the fade.
  reset-time: 3000
  # Time between action bar updates (in ticks).
  update-time: 5
  # The worlds that the action bar should be disabled in.
  disabled-in-worlds: [ ]

commands:
  top:
    # If displayname (including rank) should be used
    use-display-name: true

cannot-afford:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

cooldown:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

cannot-afford-type:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

point-names: # If you have point names that look ugly (eg g_souls) then you can map them to nice names to be shown to players.
  example_point: "Nicely Formatted Point"

use-faster-move-trigger: true # Disable if you want move trigger to detect sub-1-block movements
raytrace-distance: 80 # The distance that alt_click should check for a location

potions:
  icon:
    permanent: true
    triggered: true
  ambient:
    permanent: false
    triggered: true
  particles:
    permanent: false
    triggered: true

share-configs: true # If your configs are allowed to be used to gather data and improve the plugin. Nothing identifying (IP, Name, etc) is shared.